apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockvote-frontend
  namespace: "2401098"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockvote-frontend
  template:
    metadata:
      labels:
        app: blockvote-frontend
    spec:
      imagePullSecrets:
        - name: nexus-secret
      containers:
        - name: frontend
          image: 127.0.0.1:30085/anis-project/blockvote-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: "production"
            - name: VITE_BACKEND_BASE_URL
              value: "http://blockvote.imcc.com"
