apiVersion: v1
kind: Service
metadata:
  name: blockvote-frontend-service
  namespace: "2401098"
spec:
  selector:
    app: blockvote-frontend
  type: NodePort
  ports:
    - port: 80
      targetPort: 80