apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blockvote-ingress
  namespace: "2401098"
spec:
  ingressClassName: nginx
  rules:
    - host: blockvote.imcc.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: blockvote-backend-service
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blockvote-frontend-service
                port:
                  number: 80
